import os

# List your sample names (without file extension)
samples = ["SRR15618897", "SRR15618896", "SRR15618895", "SRR15618894", "SRR15618893", "SRR15618892", "SRR15618891", "SRR15618890", "SRR15618889", "SRR15618888", "SRR15618887", "SRR15618886"]

input_path = "/home/mif/raw_data_exercise_20250220"
 
genome_index_dir = "/home/shared/raw_data_exercise_20250220/mouse_reference/grcm38/genome" 

stages = ["raw", "filtered"]

# thread_no = 2

#######
# ALL #import glob
import os

# Define input path and output path
input_path = "/home/shared/raw_data/Ecoli_antibiotics_GSE220559"

# Get the list of sample names
files_R1 = glob.glob(os.path.join(input_path, "*_1.fastq.gz"))
samples = sorted(set(os.path.basename(f).replace("_1.fastq.gz", "") for f in files_R1))

print(samples)

genome_index_dir = "/home/shared/references/NC_000913/genome"
genome_gff = "/home/shared/references/NC_000913/NC_000913.gff3"

# Define the all rule: The final target files
rule all:
    input:
        #expand("results/trim_galore/{sample}_1_val_1.fq.gz", sample=samples),
        #expand("results/trim_galore/{sample}_2_val_2.fq.gz", sample=samples), 
        #expand("results/hisat/{sample}.bam", sample=samples), 
        "results/multiqc_report.html",
        "results/counts.txt"


# Define the trimGalore rule
rule trimGalore:
    input:
        fq1 = lambda wildcards: f"{input_path}/{wildcards.sample}_1.fastq.gz",
        fq2 = lambda wildcards: f"{input_path}/{wildcards.sample}_2.fastq.gz"
    output:
        fq1 = "results/trim_galore/{sample}_1_val_1.fq.gz",
        fq2 = "results/trim_galore/{sample}_2_val_2.fq.gz"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    params:
        quality = 25,
        length = 20
    shell:
        """
        trim_galore --paired \
        -o results/trim_galore \
        -q {params.quality} \
        -j {threads} \
        --length {params.length} \
        {input.fq1} {input.fq2}
        """

rule hisat2:
    input:
        fq1 = "results/trim_galore/{sample}_1_val_1.fq.gz",
        fq2 = "results/trim_galore/{sample}_2_val_2.fq.gz"
    output:
        sam = "results/hisat/{sample}.sam",
        bam = "results/hisat/{sample}.bam",
        bai = "results/hisat/{sample}.bam.bai",
        stat = "results/hisat/{sample}_hisat.stat"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 8
    shell:
        """
        hisat2 -p {threads} -x {genome_index_dir} --no-spliced-alignment --no-unal --no-mixed --no-discordant -1 {input.fq1} -2 {input.fq2} -S {output.sam} --new-summary --summary-file {output.stat}
        samtools view -@ {threads} -bS {output.sam} | samtools sort -@ {threads} -o {output.bam} 
        samtools index {output.bam}
        """

rule featureCounts:
    input:
        bam = expand("results/hisat/{sample}.bam", sample=samples)
    output:
        counts = "results/counts.txt",
        stats = "results/counts.txt.summary"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 8
    shell:
        """
        featureCounts -a {genome_gff} -F GTF -t CDS -g Parent -o {output.counts} -s 2 -T {threads} -p  --countReadPairs -B  {input.bam}
        """

############
#  QC part #
############

rule fastqc:
    input:
        fq1 = lambda wildcards: f"{input_path}/{wildcards.sample}_1.fastq.gz",
        fq2 = lambda wildcards: f"{input_path}/{wildcards.sample}_2.fastq.gz",  
        fq3 = "results/trim_galore/{sample}_1_val_1.fq.gz",
        fq4 = "results/trim_galore/{sample}_2_val_2.fq.gz"
    output:
        html1 = "results/fastqc/{sample}_1_fastqc.html",
        zip1  = "results/fastqc/{sample}_1_fastqc.zip",
        html2 = "results/fastqc/{sample}_2_fastqc.html",
        zip2  = "results/fastqc/{sample}_2_fastqc.zip",
        html3 = "results/fastqc/{sample}_1_val_1_fastqc.html",
        zip3  = "results/fastqc/{sample}_1_val_1_fastqc.zip",
        html4 = "results/fastqc/{sample}_2_val_2_fastqc.html",
        zip4  = "results/fastqc/{sample}_2_val_2_fastqc.zip"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    shell:
        """
            fastqc -t {threads} --outdir results/fastqc {input.fq1} {input.fq2} {input.fq3} {input.fq4}
        """ 

rule multiqc:
    input:
        expand("results/fastqc/{sample}_1_fastqc.zip", sample=samples),
        expand("results/fastqc/{sample}_1_val_1_fastqc.zip", sample=samples),
        expand("results/fastqc/{sample}_2_fastqc.zip", sample=samples),
        expand("results/fastqc/{sample}_2_val_2_fastqc.zip", sample=samples),
        "results/counts.txt.summary"
       
    output:
        "results/multiqc_report.html",
        directory("results/multiqc_data")
    log:
        "logs/multiqc.log",
    shell:
        """
        multiqc --outdir results/ {input}
        """
        
#######

# The 'all' rule defines the final targets of your pipeline
rule all:
    input:
        # expand("results/fastqc/{sample}_{stage}_fastqc.html", 
        #     sample=samples,
        #     stage=stages),
        # expand("results/fastp/{sample}_fastp.html", sample=samples),
        # expand("results/hisat2/{sample}.bam", sample=samples),
        # expand("results/hisat2/{sample}.sorted.bam", sample=samples),
        # expand("results/hisat2/{sample}.sorted.bam.bai", sample=samples),
        "results/multiqc/multiqc_report.html",

##########
# FastQC #
##########

rule fastqc:
    input:
        expand("{path}/{{sample}}_{{stage}}.fastq", path=input_path)
    output:
        html = "results/fastqc/{sample}_{stage}_fastqc.html",
        zip  = "results/fastqc/{sample}_{stage}_fastqc.zip"
    conda: "envs/preprocess_rnaseq.yaml"
    shell:
        """
            fastqc {input} --outdir results/fastqc
        """

#########
# Fastp #
#########

rule fastp:
    input: 
        expand("{path}/{{sample}}_raw.fastq", path=input_path)
    output:
        filtered = expand("{path}/{{sample}}_filtered.fastq", path=input_path),
        html = "results/fastp/{sample}_fastp.html",
        json = "results/fastp/{sample}_fastp.json"
    conda: "envs/preprocess_rnaseq.yaml"
    params:
        quality = 25,
    shell:
        """
        fastp -i {input} \
        -q {params.quality} \
        --trim_poly_g \
        --trim_poly_x \
        -o {output.filtered} \
        -h {output.html} \
        -j {output.json}
        """

##########
# HISAT2 #
##########

rule hisat2:
    input:
        fastq=expand("{path}/{{sample}}_filtered.fastq", path=input_path)
    output:
        sam="results/hisat2/{sample}.sam",
        bam="results/hisat2/{sample}.bam",
        summary="results/hisat2/{sample}_summary.txt"
    params:
        index=genome_index_dir 
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 2
    shell:
        """
        hisat2 -p {threads} -x {params.index} -U {input.fastq}  -S {output.sam} --new-summary --summary-file {output.summary}
        samtools view -b -o {output.bam} {output.sam}
        """

rule sort_bam:
    input:
        unsorted_bam="results/hisat2/{sample}.bam"
    output:
        sorted_bam="results/hisat2/{sample}.sorted.bam"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    shell:
        """
            samtools sort -@ {threads} -o {output.sorted_bam} {input.unsorted_bam}
        """
    
rule index_bam:
    input:
        sorted_bam="results/hisat2/{sample}.sorted.bam"
    output:
        bam_index="results/hisat2/{sample}.sorted.bam.bai"
    conda: "envs/preprocess_rnaseq.yaml"
    shell:
        """
            samtools index {input.sorted_bam}
        """

###########
# MULTIQC #
###########

rule multiqc:
    input:
        expand("results/fastqc/{sample}_{stage}_fastqc.zip", sample=samples, stage=stages),
        expand("results/fastp/{sample}_fastp.json", sample=samples),
        expand("results/hisat2/{sample}_summary.txt", sample=samples),
    output:
        "results/multiqc/multiqc_report.html",
        directory("results/multiqc/multiqc_data")
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
        use_input_files_only=True,  # Optional, use only a.txt and don't search folder samtools_stats for files
    log:
        "logs/multiqc.log",
    wrapper:
        "v5.8.0/bio/multiqc"